//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL.HRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.EmployeeEducationalQualifications = new HashSet<EmployeeEducationalQualification>();
            this.EmployeeEmploymentHistories = new HashSet<EmployeeEmploymentHistory>();
            this.EmployeeFamilyMembers = new HashSet<EmployeeFamilyMember>();
            this.EmployeeHealthInformations = new HashSet<EmployeeHealthInformation>();
            this.EmployeeLeaveInformations = new HashSet<EmployeeLeaveInformation>();
            this.EmployeeNomineeInformations = new HashSet<EmployeeNomineeInformation>();
            this.EmployeeReferenceInformations = new HashSet<EmployeeReferenceInformation>();
            this.EmployeeLeaveRequests = new HashSet<EmployeeLeaveRequest>();
            this.PersonalInformations = new HashSet<PersonalInformation>();
        }
    
        public long Id { get; set; }
        public string EmployeeCode { get; set; }
        public long CategoryId { get; set; }
        public long DepartmentId { get; set; }
        public long DesignationId { get; set; }
        public Nullable<long> SupervisorId { get; set; }
        public Nullable<long> ApproverId { get; set; }
        public bool IsDualApprovalApplied { get; set; }
        public long RosterId { get; set; }
        public string JobLocation { get; set; }
        public string WorkLocation { get; set; }
        public string SalaryLocation { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> AppointmentLetterNo { get; set; }
        public System.DateTime AppointmentLetterIssueDate { get; set; }
        public System.DateTime AppointmentLetterJoinDate { get; set; }
        public Nullable<decimal> JoiningLetterNo { get; set; }
        public System.DateTime JoiningDate { get; set; }
        public Nullable<decimal> ProbationaryPeriodInDays { get; set; }
        public System.DateTime JobConfirmationDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Designation Designation { get; set; }
        public virtual EmployeeCategory EmployeeCategory { get; set; }
        public virtual RosterInformation RosterInformation { get; set; }
        public virtual ICollection<EmployeeEducationalQualification> EmployeeEducationalQualifications { get; set; }
        public virtual ICollection<EmployeeEmploymentHistory> EmployeeEmploymentHistories { get; set; }
        public virtual ICollection<EmployeeFamilyMember> EmployeeFamilyMembers { get; set; }
        public virtual ICollection<EmployeeHealthInformation> EmployeeHealthInformations { get; set; }
        public virtual ICollection<EmployeeLeaveInformation> EmployeeLeaveInformations { get; set; }
        public virtual ICollection<EmployeeNomineeInformation> EmployeeNomineeInformations { get; set; }
        public virtual ICollection<EmployeeReferenceInformation> EmployeeReferenceInformations { get; set; }
        public virtual ICollection<EmployeeLeaveRequest> EmployeeLeaveRequests { get; set; }
        public virtual ICollection<PersonalInformation> PersonalInformations { get; set; }
    }
}
