//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL.HRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveApprovalStatu
    {
        public LeaveApprovalStatu()
        {
            this.EmployeeLeaveRequests = new HashSet<EmployeeLeaveRequest>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<EmployeeLeaveRequest> EmployeeLeaveRequests { get; set; }
    }
}
