//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL.HRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveType
    {
        public LeaveType()
        {
            this.EmployeeLeaveRequests = new HashSet<EmployeeLeaveRequest>();
        }
    
        public long Id { get; set; }
        public long LeavePolicyId { get; set; }
        public string Name { get; set; }
        public int NumberOfDays { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual ICollection<EmployeeLeaveRequest> EmployeeLeaveRequests { get; set; }
        public virtual LeavePolicy LeavePolicy { get; set; }
    }
}
