//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL.Security
{
    using System;
    using System.Collections.Generic;
    
    public partial class Screen
    {
        public Screen()
        {
            this.AdditionalScreenPermissions = new HashSet<AdditionalScreenPermission>();
            this.Menus = new HashSet<Menu>();
            this.RoleWiseScreenPermissions = new HashSet<RoleWiseScreenPermission>();
            this.ScreenOperations = new HashSet<ScreenOperation>();
        }
    
        public long Id { get; set; }
        public string ScreenCode { get; set; }
        public long ModuleId { get; set; }
        public string Title { get; set; }
        public string Type { get; set; }
        public string URL { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual ICollection<AdditionalScreenPermission> AdditionalScreenPermissions { get; set; }
        public virtual ICollection<Menu> Menus { get; set; }
        public virtual Module Module { get; set; }
        public virtual ICollection<RoleWiseScreenPermission> RoleWiseScreenPermissions { get; set; }
        public virtual ICollection<ScreenOperation> ScreenOperations { get; set; }
    }
}
