//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityAdministration.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItem
    {
        public byte MenuID { get; set; }
        public string Caption { get; set; }
        public byte MenuLevel { get; set; }
        public byte ItemOrder { get; set; }
        public Nullable<byte> ParentID { get; set; }
        public string ScreenCode { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public bool HasChild { get; set; }
        public System.DateTime SetOn { get; set; }
        public int SetBy { get; set; }
    
        public virtual Screen Screen { get; set; }
    }
}
